# Generated by Django 5.0.6 on 2026-06-11 15:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_market', '0002_skill_vector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='job_offer_i_lead_ma_e9c987_idx',
            old_name='job_market_job_lead_m_idx',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='full_text_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
