# Generated by Django 5.0.6 on 2026-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_market', '0006_ragchunk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='rag_chunks_source_dfe8f8_idx',
            old_name='rag_chunks_source_idx',
        ),
        migrations.AlterField(
            model_name='ragchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
